services:
  - type: web
    name: python-hunter-ultimate
    env: node
    buildCommand: npm install
    startCommand: node server/server.js
    envVars:
      - key: PORT
        value: 10000
      - key: DISCORD_WEBHOOK_URL
        value: https://discord.com/api/webhooks/1476911856919515208/mBLMw9ch8iYF8adXSCcTlz99TGVpMrhDaSEbHikBMCj38quhZKNv3VD0AVmXRe3AEPgd
    autoDeploy: true
    